name: A-core sdk CI/CD
on: 
  push:
    branches-ignore: 
      - 'doc/**'
      - 'work/**'
  pull_request:
    branches-ignore: 
      - 'doc/**'
      - 'work/**'  
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Which bump fits?'     
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'none'
env:
  ORG: ${{ github.repository_owner }}

jobs:
  call:
    uses: ${{ env.ORG }}/acore-cicd-templates/.github/workflows/acore-sdk-workflow.yml@main
    with:
      bump-type: ${{ inputs.bump-type }}
      test-registry: ghcr.io/${{ env.ORG }}/acore-sdk-test
      prod-registry: ghcr.io/${{ env.ORG }}/acore-sdk
